from __future__ import annotations

from dataclasses import dataclass
from typing import Any


ERROR_INVALID_IMAGE = 'INVALID_IMAGE'
ERROR_NO_FACE_DETECTED = 'NO_FACE_DETECTED'
ERROR_MULTIPLE_FACES_DETECTED = 'MULTIPLE_FACES_DETECTED'
ERROR_IMAGE_TOO_BLURRY = 'IMAGE_TOO_BLURRY'
ERROR_FACE_TOO_SMALL = 'FACE_TOO_SMALL'
ERROR_POSE_INVALID = 'POSE_INVALID'
ERROR_FACE_OCCLUDED = 'FACE_OCCLUDED'
ERROR_HEAD_CROPPED = 'HEAD_CROPPED'
ERROR_FACIAL_KEYPOINTS_INCOMPLETE = 'FACIAL_KEYPOINTS_INCOMPLETE'
ERROR_HEADWEAR_DETECTED = 'HEADWEAR_DETECTED'
ERROR_HAND_OCCLUSION = 'HAND_OCCLUSION'
ERROR_EYE_OCCLUDED = 'EYE_OCCLUDED'
ERROR_NOT_SINGLE_FRONTAL_FACE = 'NOT_SINGLE_FRONTAL_FACE'
ERROR_IMAGE_TOO_SMALL = 'IMAGE_TOO_SMALL'
ERROR_FILE_NOT_FOUND = 'FILE_NOT_FOUND'
ERROR_INVALID_ARGUMENT = 'INVALID_ARGUMENT'
ERROR_PROCESS_FAILED = 'PROCESS_FAILED'


@dataclass
class AppException(Exception):
    message: str
    error_code: str = ERROR_PROCESS_FAILED
    status_code: int = 400
    data: Any = None

    def __str__(self) -> str:
        return self.message
